# Generated by Django 5.0.3 on 2024-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_bid_by_alter_listing_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
